name = input("Enter name:")
train_no = input("Enter train number:")
source = input("Enter the pickup place:")
destination = input("Enter the destination place:")
seat = input("Enter the seat number:")
coach = input("Enter the coach:")

print("\nName:",name)
print("Train_no:",train_no)
print("Source:",source)
print("Destination:",destination)
print("Seat:",seat)
print("Coach:",coach)
print("-----------------")
print("Happy Journey")
